### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JackHeroFly** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#1]
Hello author,
    Thank you for your source code. Could you provide a copy of the processed data to reproduce your research work?

**Comment by junyuchen245** [comment]
Hi @JackHeroFly,

Unfortunately, due to certain restrictions, we cannot share those datasets with you. 

However, we are currently testing TransMorph and the baselines on IXI dataset for atlas-to-patient brain MR registration (https://brain-development.org/ixi-dataset/). This dataset was made available under the CC BY-SA 3.0 license, which means it is possible to redistribute our preprocessed IXI dataset. We will make this dataset publicly available once we are done with the testing.

Junyu

**Comment by JackHeroFly** [comment]
Thank you very much. Is Transmorph just applicable to mono-modal registration task?Have you done any experiments on multi-modal registration task?

**Comment by junyuchen245** [comment]
TransMorph is capable of multi-modal registration. We have provided two multi-modal loss functions, MIND-SSC and mutual information, in the “losses.py” script (https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/main/TransMorph/losses.py). 

The XCAT-to-CT registration task described in the paper can also be think of as a multi-modal registration task.

Junyu

**Comment by junyuchen245** [comment]
Hi @JackHeroFly 

We just made our preprocessed IXI dataset available! Check out the following page for more information and the download link for the dataset.

https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/main/TransMorph_on_IXI.md

Junyu
