### ISSUE TITLE
Deformation field not smooth

### ISSUE THREAD

**Issue by kvttt** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#12]
Hi Chen, 

First off, thank you for making the code and datasets for OASIS available! I have been trying to apply the pre-trained model on the OASIS data you provided. For the output, I convert the deformation field in the .npz file into a .nii file in order to visualize the result in ITK-SNAP. However, the result does not seem very smooth which is frustrating. 

Attached is the screenshot of the deformation field:
![Screenshot from 2022-04-01 16-07-56](https://user-images.githubusercontent.com/99367900/161334600-8417bdd2-5896-4cd9-a466-db50b2b34845.png)

I am wondering what is causing this issue. Thank you in advance for your help and I look forward to hear back from you!

**Comment by junyuchen245** [comment]
Hi @kvttt ,

Thank you for your interest in our work. Your observation is correct. Plain TransMorph does not guarantee a diffeomorphism. The smoothness of the deformation field was simply imposed by the regularizer during training. You could use TransMorph-bspl or TransMorph-diff to get a smoother deformation. However, we have not trained and tested those variants on the OASIS dataset. So you might need to train them from scratch.

Typically, for learning-based registration methods, a diffeomorphism is guaranteed by assuming a stationary velocity field. However, we observed that using SVF might degrade performance. Lately, we developed a new model called TransMorph-cascade (currently ranked 1st on task03 of the 2021 L2R challenge), which allows us to impose some smoothness without compromising performance (in terms of Dice). Since it has not been published yet (and we are unsure if we will), we are not going to share the source code for it for now. Having said that, if we decide not to publish it, I will include the source code and pre-trained weights of TransMorph-cascade in this repository.

Thanks,
Junyu

**Comment by kvttt** [comment]
Thank you so much for the detailed explanation! I will go ahead and try TransMorph-bspl and TransMorph-diff.

**Comment by bhosalems** [comment]
Hi @kvttt ,

Do you have the code for visualizing the deformation field?

Thanks in advance.

**Comment by kvttt** [comment]
Hi @bhosalems, I think I do. I will pull it up right now and paste a snippet here later today.

**Comment by bhosalems** [comment]
Thanks @kvttt , let me try this today night. will revert back.

**Comment by xiaogengen-007** [comment]
> Hi @bhosalems, I guess you would need to do something like this:
> 
> ```
> import nibabel as nib
> import numpy as np
> 
> img = nib.load('target.nii.gz')  # you would need the target .nii file for affine and header 
> flow = np.laod('filename.npz')['arr_0']  # load the npz file and get data
> flow = flow.transpose(2, 3, 4, 0, 1)  # this is to make the dimension agree with nifti's 
> flow_img = nib.Nifti1Image(flow, img.affine, img.header)
> nib.save(flow_img, 'filename.nii.gz')
> ```
> 
> It is also possible to just modify the inference script and create a NIFTI image from there. Let me know if you run into any problems! Hope this helps!

Hi @kvttt ,
I am also interested in the visualization you made for the deformation field. Did you directly import the (3,H,W,D) flow field into ITK-SNAP or did you first convert the flow field into warped grids and then visualize the grids in ITK-SNAP?

From the snippet you gave, it seems that ITK-SNAP can directly visualize the flow field. However, I was unable to find that function. Could you please give me some hints?

Thank you so much in advance!

**Comment by kvttt** [comment]
@xiaogengen-007, I didn't do anything special. Once some transpose is performed to the flow field and the deformation field is saved as a *.nii.gz file, it can be open directly in ITK-SNAP. I suppose you are using ITK-SNAP in command line. For me, I just dragged the file into ITK-SNAP.
