### ISSUE TITLE
Train_affine "phan.pkl" has a question.

### ISSUE THREAD

**Issue by kimtaeuk-AI** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#13]
Hello. Thank you for the good code.
I'm going to study with this code. Can I know what the 'phan.pkl' file is in train_affine?
I don't know where it is.

Thank you :)

**Comment by junyuchen245** [comment]
Hi @kimtaeuk-AI ,

Thank you for your interest in our project. The affine network was tested with an in-house dataset from JHU. Due to various restrictions, we cannot share the dataset with others. You are welcome to test it with your own data.

The deformable network was tested on various publicly available datasets. You are welcome to try those.

Junyu

**Comment by kimtaeuk-AI** [comment]
Ah~ Thank you for letting me know. 
Have a nice day !
