### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ppegiosk** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#2]
Hi,

Great paper and thanks for sharing your source code ! It works when using the default input size but I am getting an error when I am trying to use different input sizes. Note that I change the size also in the config file.
Do you have any idea what I am doing wrong ?

Example:

#x = torch.rand((1,2, 160, 192, 224))
x = torch.rand((1,2, 192, 192, 208))

out, flow = model.forward(x)

print(out.size())
print(flow.size())

Error:
x = x.view(B, H // window_size[0], window_size[0], W // window_size[1], window_size[1], L // window_size[2], window_size[2], C)
RuntimeError: shape '[1, 10, 5, 8, 6, 7, 7, 6]' is invalid for input of size 808704

**Comment by junyuchen245** [comment]
Hi @ppegiosk 

Refer to the network architecture diagram below. Because the encoder downsamples the input by a factor of 32, the size of the input must be divisible by 32. As a result, the size 208 is invalid.

Additionally, it is recommended that you configure the window size (for Swin Transformer) to be the same as the input size after 32-fold downsampling. For example, an optimal window size for a 160 x 192 x 192 input would be (160/32, 192/32, 192/32) = (5, 6, 6).

You can set the window size [here](https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/03ca29746f9414e02545a0786924a66a9764d0cf/TransMorph/models/configs_TransMorph.py#L47) and the input size [here](https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/03ca29746f9414e02545a0786924a66a9764d0cf/TransMorph/models/configs_TransMorph.py#L59).

![image](https://user-images.githubusercontent.com/17306891/144484271-6518fea4-5aa2-4d4b-92f3-d79f8967ac83.png)

Let me know if you have other questions.

Junyu

**Comment by ppegiosk** [comment]
Thanks a lot for your quick reply. I will have a better look into that.

I have kind of the same problem with your previous work/model vit-v-net. I am getting an error when I tried 
the input size mentioned before (192, 192, 208):

Error:
x = torch.cat([x, skip], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Got 12 and 13 in dimension 4 (The offending index is 1)

**Comment by junyuchen245** [comment]
The same principle applies to ViT-V-Net. Check out the code [here](https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/blob/e9637b7414ddf4568723d70d9417923831ee8ab7/ViT-V-Net/models.py#L124) and [here](https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/blob/f7d41fcfa07c13477a9c271ab74f6f4f4ba48c7d/ViT-V-Net/models.py#L283), where "down_factor" is the downsampling factor of the CNN encoder and "patch_size" is the size of a patch used in the Vision Transformer. 

In the [default setting](https://github.com/junyuchen245/ViT-V-Net_for_3D_Image_Registration_Pytorch/blob/main/ViT-V-Net/configs.py), the input size is first downsampled by a factor of 2^down_factor=4 using the CNN encoder, then by a patch size of 8 for self-attention. 
Therefore, in total, the image size should be divisible by 4*8=32. As a result, 208 is not a valid size for ViT-V-Net as well. You may zero-pad the image to make it 224.
