### ISSUE TITLE
Hi! How to normalize the data?

### ISSUE THREAD

**Issue by ljdream0710** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#3]
Thank you for sharing you code. Could you tell me how to normalize the data?
The images are normalized to [-1,1] or [0,1]?

**Comment by junyuchen245** [comment]
The brain MRI datasets were first preprocessed by using [FreeSurfer](https://surfer.nmr.mgh.harvard.edu/), where skull stripping, affine registration, etc. were performed. We then divided the intensity values by 255 so that the intensity values were normalized into a range of [0, 1].

The intensity values of CT images were first clipped by [-1000, 1000] HU and then normalized by the minimum and maximum values into a range of [0,1].

FYI, we are currently testing TransMorph and the baseline models on the [IXI dataset](https://brain-development.org/ixi-dataset/) for atlas-to-patient registration. Once we finish testing, we will make our preprocessed IXI dataset and the pre-trained models publicly available. We have already uploaded a few pre-trained models to Google Drive, and you can find the descriptions of the models and the preprocessed dataset here: [TransMorph on IXI](https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/main/TransMorph_on_IXI.md).
