### ISSUE TITLE
Data Size！

### ISSUE THREAD

**Issue by SLKaMiHi** [junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration#4]
Hi：
Thank you very much for the source code. Due to memory limitations, I cannot allow large-size data. Therefore, I would like to ask how to adjust the parameters if I want to run data with a size of (96, 112, 96). Or the smallest image I can run and how to adjust the parameters. Thank you so much!

**Comment by junyuchen245** [comment]
Hi @SLKaMiHi

The shape of the input should be divisible by 32. Therefore, 112 would not be a valid size. Additionally, 96/32=3, which is smaller than what we used for patch size (i.e., 4). I would recommend you to try TransMorph-small:
https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/246795ebf3086238b7605f495e181d704ba04c48/TransMorph/models/configs_TransMorph.py#L235
https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/246795ebf3086238b7605f495e181d704ba04c48/TransMorph/models/TransMorph.py#L959
https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/246795ebf3086238b7605f495e181d704ba04c48/TransMorph/train_TransMorph.py#L47

Also, you will need to zero-pad 112 so that it becomes 128. You will also need to change the patch size to be 2 or 3 (i.e., line 242):
https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/246795ebf3086238b7605f495e181d704ba04c48/TransMorph/models/configs_TransMorph.py#L235-L242


Thanks,
Junyu

**Comment by Yangxi12** [comment]
Hi @junyuchen245 
 what is your model's input data size ?
Thank you very much!
